run:
  timeout: 5m
  tests: true

service:
  golangci-lint-version: latest # use latest version for Go 1.24 support

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocyclo

  disable:
    - gosec # Run separately in security workflow
    - errcheck # Temporarily disabled due to intentional error ignoring in audit logging
    - goconst # Temporarily disabled - strings used in limited contexts don't need constants

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goimports:
    local-prefixes: hosts-manager
  
  gocyclo:
    min-complexity: 50
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - goconst
        - errcheck
  
  max-issues-per-linter: 0
  max-same-issues: 0