package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/brandonhon/hosts-manager/pkg/platform"

	"gopkg.in/yaml.v3"
)

type Config struct {
	General    General            `yaml:"general"`
	Categories map[string]string  `yaml:"categories"`
	Profiles   map[string]Profile `yaml:"profiles"`
	UI         UI                 `yaml:"ui"`
	Backup     Backup             `yaml:"backup"`
	Export     Export             `yaml:"export"`
}

type General struct {
	DefaultCategory string `yaml:"default_category"`
	AutoBackup      bool   `yaml:"auto_backup"`
	DryRun          bool   `yaml:"dry_run"`
	Verbose         bool   `yaml:"verbose"`
	Editor          string `yaml:"editor"`
}

type Profile struct {
	Description string   `yaml:"description"`
	Categories  []string `yaml:"categories"`
	Default     bool     `yaml:"default"`
}

type UI struct {
	ColorScheme     string            `yaml:"color_scheme"`
	ShowLineNumbers bool              `yaml:"show_line_numbers"`
	PageSize        int               `yaml:"page_size"`
	KeyBindings     map[string]string `yaml:"key_bindings"`
}

type Backup struct {
	Directory       string `yaml:"directory"`
	MaxBackups      int    `yaml:"max_backups"`
	RetentionDays   int    `yaml:"retention_days"`
	CompressionType string `yaml:"compression_type"`
}

type Export struct {
	DefaultFormat string            `yaml:"default_format"`
	Formats       map[string]Format `yaml:"formats"`
}

type Format struct {
	Extension string `yaml:"extension"`
	Template  string `yaml:"template"`
}

func DefaultConfig() *Config {
	return &Config{
		General: General{
			DefaultCategory: "custom",
			AutoBackup:      true,
			DryRun:          false,
			Verbose:         false,
			Editor:          getDefaultEditor(),
		},
		Categories: map[string]string{
			"development": "Development environments and local services",
			"staging":     "Staging and testing environments",
			"production":  "Production services and critical infrastructure",
			"custom":      "User-defined entries",
			"vpn":         "VPN and remote access configurations",
			"blocked":     "Blocked hosts for security or productivity",
		},
		Profiles: map[string]Profile{
			"minimal": {
				Description: "Minimal profile with essential entries only",
				Categories:  []string{"production"},
				Default:     false,
			},
			"development": {
				Description: "Development profile with dev and staging environments",
				Categories:  []string{"development", "staging"},
				Default:     false,
			},
			"full": {
				Description: "Full profile with all categories enabled",
				Categories:  []string{"development", "staging", "production", "custom"},
				Default:     true,
			},
		},
		UI: UI{
			ColorScheme:     "auto",
			ShowLineNumbers: true,
			PageSize:        20,
			KeyBindings: map[string]string{
				"quit":      "q",
				"help":      "?",
				"edit":      "e",
				"toggle":    "space",
				"delete":    "d",
				"search":    "/",
				"next_page": "n",
				"prev_page": "p",
				"refresh":   "r",
				"save":      "s",
			},
		},
		Backup: Backup{
			Directory:       "",
			MaxBackups:      10,
			RetentionDays:   30,
			CompressionType: "gzip",
		},
		Export: Export{
			DefaultFormat: "yaml",
			Formats: map[string]Format{
				"yaml": {
					Extension: ".yaml",
					Template:  "{{.}}",
				},
				"json": {
					Extension: ".json",
					Template:  "{{.}}",
				},
				"hosts": {
					Extension: ".hosts",
					Template:  "# Generated by hosts-manager\n{{range .Categories}}{{if .Enabled}}# {{.Name}}\n{{range .Entries}}{{if .Enabled}}{{.IP}} {{join .Hostnames \" \"}}{{if .Comment}} # {{.Comment}}{{end}}\n{{end}}{{end}}\n{{end}}{{end}}",
				},
			},
		},
	}
}

// getDefaultEditor picks the editor to seed a new config with.
//
// $VISUAL takes precedence over $EDITOR, which is the POSIX convention: $EDITOR
// may name a line editor suitable for a dumb terminal, while $VISUAL names the
// full-screen one to use when the terminal can support it. This checked them
// the other way round, so anyone who sets both got the fallback rather than
// their preferred editor.
func getDefaultEditor() string {
	if editor := os.Getenv("VISUAL"); editor != "" {
		return editor
	}
	if editor := os.Getenv("EDITOR"); editor != "" {
		return editor
	}
	return "nano"
}

func Load() (*Config, error) {
	p := platform.New()
	configDir := p.GetConfigDir()
	configPath := filepath.Join(configDir, "config.yaml")

	// Both paths converge below. They used to be separate, and only the
	// read path filled in the backup directory — so the very first run
	// returned a config with an empty one and every command with AutoBackup
	// enabled (the default) failed at os.MkdirAll("").
	config := DefaultConfig()
	firstRun := false

	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		firstRun = true
	} else {
		data, err := os.ReadFile(configPath)
		if err != nil {
			return nil, fmt.Errorf("failed to read config file: %w", err)
		}
		if err := yaml.Unmarshal(data, config); err != nil {
			return nil, fmt.Errorf("failed to parse config file: %w", err)
		}
	}

	// Written before the backup directory is resolved, so the file on disk
	// keeps an empty value. An empty directory means "work it out from the
	// data dir at load time", which survives the home directory moving; a
	// resolved absolute path baked into the file would not.
	if firstRun {
		if err := Save(config); err != nil {
			return config, fmt.Errorf("failed to create default config: %w", err)
		}
	}

	if config.Backup.Directory == "" {
		config.Backup.Directory = filepath.Join(p.GetDataDir(), "backups")
	}

	// Validate the loaded configuration
	validator := NewValidator()
	if err := validator.Validate(config); err != nil {
		return nil, fmt.Errorf("configuration validation failed: %w", err)
	}
	emitWarnings(validator)

	return config, nil
}

// emitWarnings reports non-fatal configuration problems to stderr. They are
// surfaced once at load time so the user learns about them without any
// command being blocked.
func emitWarnings(validator *ConfigValidator) {
	for _, warning := range validator.Warnings() {
		fmt.Fprintf(os.Stderr, "Warning: %s\n", warning)
	}
}

func Save(config *Config) error {
	// Validate configuration before saving
	validator := NewValidator()
	if err := validator.Validate(config); err != nil {
		return fmt.Errorf("configuration validation failed: %w", err)
	}

	p := platform.New()
	configDir := p.GetConfigDir()

	if err := os.MkdirAll(configDir, 0700); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "config.yaml")
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	if err := os.WriteFile(configPath, data, 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}
