name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., v0.1.0)'
        required: true
        type: string

env:
  GO_VERSION: 'stable'

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION=${{ github.event.release.tag_name }}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build release binaries
        run: VERSION=${{ env.VERSION }} make release

      - name: Create distribution packages
        run: VERSION=${{ env.VERSION }} make dist

      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          body: |
            ## Release ${{ env.VERSION }}
            
            Cross-platform binaries and source code for hosts-manager.
            
            ### 📦 Available Downloads
            
            **Compiled Binaries (both .tar.gz and .zip formats):**
            - `hosts-manager-${{ env.VERSION }}-linux-amd64.{tar.gz,zip}` - Linux x64
            - `hosts-manager-${{ env.VERSION }}-linux-arm64.{tar.gz,zip}` - Linux ARM64
            - `hosts-manager-${{ env.VERSION }}-darwin-amd64.{tar.gz,zip}` - macOS Intel
            - `hosts-manager-${{ env.VERSION }}-darwin-arm64.{tar.gz,zip}` - macOS Apple Silicon
            - `hosts-manager-${{ env.VERSION }}-windows-amd64.{tar.gz,zip}` - Windows x64
            
            **Source Code:**
            - `hosts-manager-${{ env.VERSION }}-source.tar.gz` - Complete source code archive
            - `hosts-manager-${{ env.VERSION }}-source.zip` - Complete source code archive
            
            ### 🚀 Quick Installation
            
            **Linux/macOS:**
            ```bash
            # Download and extract (replace with your platform)
            curl -L -o hosts-manager.tar.gz https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/hosts-manager-${{ env.VERSION }}-linux-amd64.tar.gz
            tar -xzf hosts-manager.tar.gz
            sudo mv hosts-manager /usr/local/bin/hosts-manager
            chmod +x /usr/local/bin/hosts-manager
            ```
            
            **Windows:**
            Download the appropriate `.zip` file for your architecture and add the extracted `hosts-manager.exe` to your PATH.
            
            ### 🔐 Checksums
            All files are verified with SHA-256 checksums in `checksums.txt`.

      - name: Upload build artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: hosts-manager-${{ env.VERSION }}
          path: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt